### ISSUE TITLE
Unable to build the source

### ISSUE THREAD

**Issue by jade767** [ChamaraIC/Tachometer#1]
Hello,

Firstly, let me say that this graphic is wonderful! It's the gauge that was missing from PowerBI 👍 

However, I'm trying to build the source you've shared, but I'm unable to do so with lots of references missing. Can you check in the entire source folder? 

I'm interested in playing with the showCalloutValue as the graphic hides the number on the smallest setting.

Kind Regards,

Bram

![image](https://cloud.githubusercontent.com/assets/7336598/22329287/e0a662d4-e3c0-11e6-9a56-46c4dc6875da.png)

**Comment by ChamaraIC** [comment]
Hi Bram,
Actually the source code is complete here. However, it is built using the deprecated Dev Tools, so you may not be able to do anything with it as is. I am working on migrating it to the new CLI environment but that is not straight forward. CLI environment did not even support some of the references we had couple of months back but with January release there is better support. Anyway, I am yet to do the migration. 
Regarding hiding callouts and other labels, it is a requirement from Power BI team that we do it that way. When we initially submitted the visual to Microsoft, we were asked to work on this feature before publication (for example, the gauge visual from Microsoft also behave the same).
Thank you,
Chamara

**Comment by ChamaraIC** [comment]
New CLI code checked in.
