### ISSUE TITLE
Tachometer does not respond when a value becomes blank

### ISSUE THREAD

**Issue by ChamaraIC** [ChamaraIC/Tachometer#3]
When used with a filter, if a value becomes blank, Tachometer remains at the previous value.

**Comment by ChamaraIC** [comment]
Please find a temporary solution here https://github.com/ChamaraIC/Tachometer/blob/master/dist/TachometerTmp.pbiviz

**Comment by pauloewerton** [comment]
I definitive fix for this would be great. Thanks.

**Comment by ChamaraIC** [comment]
@pauloewerton , we have already submitted the fix to Microsoft and have learnt that it will be available for public (through visuals gallery) on 04/18/2017.
