### ISSUE TITLE
Setting up the environment

### ISSUE THREAD

**Issue by szekszardi** [ChamaraIC/Tachometer#5]
Hello,

I have tried to setup the development environment to be able to compile this fantastic Tachometer visual. 
I do:
 pbiviz new TachometerCustom
cd TachometerCustom
pbiviz package

Everithing is working fine, I get the package file.

But if I copy the files from git repository over the files in my folder, I get this error:

 info   Building visual...
 error  VALIDATION   Invalid API Version v1.4.0

I am stacked here even if I update the api.
Please help to create the environment or guide me where to find a step - by - step tutorial to set it up.
Thank you very much.
Attila.

**Comment by ChamaraIC** [comment]
Hi Attila,

Please check the section on updating the API in the following documentation from Power BI Team. https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/usage.md#updating-your-existing-api-version 
This should resolve your issue. Please let us know.
Thank you

**Comment by szekszardi** [comment]
Hello

I just had to install the dependencies. Then It worked.
Thank you very much.
Best Regards.
Attila

2017-06-09 14:26 GMT-04:00 Indika Chamara (IC) Ranasinghe <
notifications@github.com>:
